### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by nidhimundra** [xmar/360Degree_Head_Movement_Dataset#2]
I am getting this error on building the project:

`LibAvWrapper/libLibAvWrapper.a(VideoReader.cpp.o): In function `IMT::LibAv::VideoReader::RunDecoderThread()':
VideoReader.cpp:(.text+0x18ce): undefined reference to `avcodec_send_packet'
VideoReader.cpp:(.text+0x1d15): undefined reference to `avcodec_send_packet'
VideoReader.cpp:(.text+0x1ffa): undefined reference to `avcodec_send_packet'
LibAvWrapper/libLibAvWrapper.a(VideoReader.cpp.o): In function `IMT::LibAv::VideoFrame::AvCodecReceiveFrame(AVCodecContext*)':
VideoReader.cpp:(.text._ZN3IMT5LibAv10VideoFrame19AvCodecReceiveFrameEP14AVCodecContext[_ZN3IMT5LibAv10VideoFrame19AvCodecReceiveFrameEP14AVCodecContext]+0x23): undefined reference to `avcodec_receive_frame'
collect2: error: ld returned 1 exit status
CMakeFiles/OSVRClientTest.dir/build.make:204: recipe for target 'OSVRClientTest' failed
make[2]: *** [OSVRClientTest] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/OSVRClientTest.dir/all' failed
make[1]: *** [CMakeFiles/OSVRClientTest.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`

FFMPEG Version:

`ffmpeg version 3.3.4 Copyright (c) 2000-2017 the FFmpeg developers
built with gcc 6.3.0 (Ubuntu/Linaro 6.3.0-18ubuntu2~16.04) 20170519
configuration: --prefix=/home/an/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/an/ffmpeg_build/include --extra-ldflags=-L/home/an/ffmpeg_build/lib --extra-libs='-lpthread -lm' --bindir=/home/an/bin --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree
libavutil      55. 58.100 / 55. 58.100
libavcodec     57. 89.100 / 57. 89.100
libavformat    57. 71.100 / 57. 71.100
libavdevice    57.  6.100 / 57.  6.100
libavfilter     6. 82.100 /  6. 82.100
libswscale      4.  6.100 /  4.  6.100
libswresample   2.  7.100 /  2.  7.100
libpostproc    54.  5.100 / 54.  5.100`

**Comment by marvsz** [comment]
Hi I am having the same issue you are having. Did you figure it out by any chance?

**Comment by nidhimundra** [comment]
Hi, We used a different version of ffmpeg, and also copied all the ffmpeg binaries to lib, share, include and bin folders.
